server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/run?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
logging:
  level:
    com:
      samchen:
        gorun:
          mapper: debug
### Redis 相关配置
#redis:
#  host: localhost
#  port: 6379
#  timeout: 10000
#  database: 0
#  lettuce:
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.samchen.gorun.entity
  configuration:
    map-underscore-to-camel-case: true
